-- AlterTable
ALTER TABLE "NeighborhoodMarketData" ALTER COLUMN "salePricePerSqm" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "rentPricePerSqm" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Property" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "administrationFee" SET DATA TYPE DOUBLE PRECISION;
